### ISSUE TITLE
Massive uploads, memory issues.

### ISSUE THREAD

**Issue by paulcanning** [Superbalist/flysystem-google-storage#32] opened 2016-07-18 11:15 UTC
I am looking to do some huge uploads (using elFidner and Google Cloud Storage) and it looks like I am running out of memory when doing so.

elFinder's debug information shows that it's using a peak memory of 5mb.

The upload is chunked into 10mb segments as well.

I'm wondering if there is anything that can be done?

Testing uploading to a local file system, everything is OK, and a file that is under 2gb (the current memory limit of PHP) also works, but I'm wondering if there is a way to have the upload streamed as bits, rather then the whole file?

**Comment by paulcanning** [comment] 2016-07-29 10:48
Hello?

**Comment by matthewgoslett** [comment] 2016-08-08 08:51
Duplicate of https://github.com/Superbalist/flysystem-google-storage/issues/34

**Closed by matthewgoslett** 2016-08-08 08:51 UTC
Labels: duplicate
